server:
  port: 8090
spring:
  data:
    mongodb:
      username: zhomart
      password: zhoma005
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${server.port}