server:
  port: 8070
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product
    username: postgres
    password: zhoma005
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
   customer-url: http://localhost:8222/api/v1/customers
   payment-url:  http://localhost:8222/api/v1/payments
   product-url:  http://localhost:8222/api/v1/products
