services:
  postgresql:
    container_name: ms_pg_sql
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zhoma005

      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
        - '5433:5432'
    networks:
      - microservices-net
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zhomart
      - MONGO_INITDB_ROOT_PASSWORD=zhoma005

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=zhomart
      - ME_CONFIG_MONGODB_ADMINPASSWORD=zhoma005
      - ME_CONFIG_MONGODB_SERVER=mongodb

  mail-dev:
    container_name: ms-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  microservices-net:
    driver: bridge


volumes:
  postgres:
  mongo:
